### PR TITLE
[OSPRH-6312] Remove memcached from autoscaling

### PR DESCRIPTION
**Pull request by vyzigold**
During investigatin of issues with [OSPRH-6312](https://issues.redhat.com//browse/OSPRH-6312) we discovered, that memcached in fact isn't required for aodh. Because it was a required parameter, it actually caused additional unnecessary issues. This PR removes memcached from the autoscaling api, from all example CRs and from kuttl tests.

rh-jira: https://issues.redhat.com/browse/OSPRH-6312

### CODE REVIEW

**Comment by paramite** [comment]
Did not test this, but code looks legit.

**Comment by jlarriba** [comment]
let's see how it runs through CI

**Comment by jlarriba** [comment]
recheck

**Pull request merged**
