### PR TITLE
Run default-telemetry after edpm is deployed

### PR DESCRIPTION
**Pull request by vyzigold**
This should allow us to discover more issues.

### CODE REVIEW

**Comment by vyzigold** [comment]
This is expected to fail the CI until https://github.com/openstack-k8s-operators/telemetry-operator/pull/408 is merged. By failing the CI we know this PR works as intended.

**Comment by vyzigold** [comment]
This failed as expected.

**Comment by vyzigold** [comment]
recheck - The fix PR is merged, so now this should succeed in the CI

**Review by elfiesmelfie — APPROVED** [review]

**Pull request merged**
