### PR TITLE
Add github.com/gibizer/operator-lint

### PR DESCRIPTION
**Pull request by gibizer**
To be able to add that in the same way as in other service-operators the existing operator-lint target is renamed to kube-linter and operator-lint target now run github.com/gibizer/operator-lint.

The kube-linter target extended to ensure that the kube-linter binary is installed locally.

The operator-lint need go.work setup to be able to check the ./api module properly so a gowork make target is added and go.work is ignored in .gitignore.

The go work sync found a conflict in dependencies between the main and the ./api module so github.com/kr/pretty is bumped to v0.2.1 to resolve that.

Then the operator-lint findings are fixed.

### CODE REVIEW

**Comment by gibizer** [comment]
> Thanks for the PR! Can you please run pre-commit locally so that the CI job does not fail?

Hm. I run it locally and only the gotest target fails that I haven't touched and that is passing in the github workflow.
```
$ pre-commit run -a
check for added large files..............................................Passed
fix utf-8 byte order marker..............................................Passed
check for case conflicts.................................................Passed
check that executables have shebangs.....................................Passed
check that scripts with shebangs are executable..........................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
detect destroyed symlinks................................................Passed
check yaml...............................................................Passed
check json...............................................................Passed
detect private key.......................................................Passed
fix end of files.........................................................Passed
don't commit to branch...................................................Passed
trim trailing whitespace.................................................Passed
make-gofmt...............................................................Passed
make-govet...............................................................Passed
make-gotest..............................................................Failed
- hook id: make-gotest
- exit code: 2

if [ -d  "/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO" ]; then \
	echo "Ci tools exists"; \
	pushd "/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO"; \
	git pull --rebase; \
	popd; \
else \
	git clone https://github.com/openstack-k8s-operators/openstack-k8s-operators-ci "/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO"; \
fi
Ci tools exists
~/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO ~/upstream/git/openstack-k8s-operators/ceilometer-operator
Already up to date.
~/upstream/git/openstack-k8s-operators/ceilometer-operator
/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO/test-runner/gotest.sh
+ GOWORK=off
++ dirname /home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO/test-runner/gotest.sh
+ BASE_DIR=/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO/test-runner
+ cd /home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/CI_TOOLS_REPO/test-runner/../..
+ MODULE_DIR=.
+ '[' -n '' ']'
+ pushd .
~/upstream/git/openstack-k8s-operators/ceilometer-operator ~/upstream/git/openstack-k8s-operators/ceilometer-operator
+ GOWORK=off
+ go test -mod=mod -v ./...
?   	github.com/openstack-k8s-operators/ceilometer-operator	[no test files]
=== RUN   TestAPIs
Running Suite: Controller Suite
===============================
Random Seed: 1679573502
Will run 0 of 0 specs

STEP: bootstrapping test environment
2023-03-23T13:11:42+01:00	DEBUG	controller-runtime.test-env	starting control plane
2023-03-23T13:11:42+01:00	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 0, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:329
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:259
github.com/openstack-k8s-operators/ceilometer-operator/controllers.glob..func1
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:60
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64
github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/suite_nodes.go:25
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runBeforeSuite
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:123
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:63
github.com/onsi/ginkgo/internal/suite.(*Suite).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79
github.com/onsi/ginkgo.runSpecsWithCustomReporters
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245
github.com/onsi/ginkgo.RunSpecs
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:220
github.com/openstack-k8s-operators/ceilometer-operator/controllers.TestAPIs
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:46
testing.tRunner
	/usr/local/go/src/testing/testing.go:1446
2023-03-23T13:11:42+01:00	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 1, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:329
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:259
github.com/openstack-k8s-operators/ceilometer-operator/controllers.glob..func1
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:60
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64
github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/suite_nodes.go:25
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runBeforeSuite
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:123
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:63
github.com/onsi/ginkgo/internal/suite.(*Suite).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79
github.com/onsi/ginkgo.runSpecsWithCustomReporters
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245
github.com/onsi/ginkgo.RunSpecs
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:220
github.com/openstack-k8s-operators/ceilometer-operator/controllers.TestAPIs
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:46
testing.tRunner
	/usr/local/go/src/testing/testing.go:1446
2023-03-23T13:11:42+01:00	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 2, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:329
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:259
github.com/openstack-k8s-operators/ceilometer-operator/controllers.glob..func1
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:60
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64
github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/suite_nodes.go:25
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runBeforeSuite
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:123
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:63
github.com/onsi/ginkgo/internal/suite.(*Suite).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79
github.com/onsi/ginkgo.runSpecsWithCustomReporters
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245
github.com/onsi/ginkgo.RunSpecs
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:220
github.com/openstack-k8s-operators/ceilometer-operator/controllers.TestAPIs
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:46
testing.tRunner
	/usr/local/go/src/testing/testing.go:1446
2023-03-23T13:11:42+01:00	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 3, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:329
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:259
github.com/openstack-k8s-operators/ceilometer-operator/controllers.glob..func1
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:60
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64
github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/suite_nodes.go:25
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runBeforeSuite
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:123
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:63
github.com/onsi/ginkgo/internal/suite.(*Suite).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79
github.com/onsi/ginkgo.runSpecsWithCustomReporters
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245
github.com/onsi/ginkgo.RunSpecs
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:220
github.com/openstack-k8s-operators/ceilometer-operator/controllers.TestAPIs
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:46
testing.tRunner
	/usr/local/go/src/testing/testing.go:1446
2023-03-23T13:11:42+01:00	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 4, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:329
sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:259
github.com/openstack-k8s-operators/ceilometer-operator/controllers.glob..func1
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:60
github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113
github.com/onsi/ginkgo/internal/leafnodes.(*runner).run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64
github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/suite_nodes.go:25
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runBeforeSuite
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:123
github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:63
github.com/onsi/ginkgo/internal/suite.(*Suite).Run
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79
github.com/onsi/ginkgo.runSpecsWithCustomReporters
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245
github.com/onsi/ginkgo.RunSpecs
	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:220
github.com/openstack-k8s-operators/ceilometer-operator/controllers.TestAPIs
	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:46
testing.tRunner
	/usr/local/go/src/testing/testing.go:1446
Failure [0.001 seconds]
[BeforeSuite] BeforeSuite 
/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:49

  Unexpected error:
      <*fmt.wrapError | 0xc0006127a0>: {
          msg: "unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
          err: <*fmt.wrapError | 0xc000612780>{
              msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory",
              err: <*fs.PathError | 0xc0002d1dd0>{
                  Op: "fork/exec",
                  Path: "/usr/local/kubebuilder/bin/etcd",
                  Err: <syscall.Errno>0x2,
              },
          },
      }
      unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
  occurred

  /home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:61
------------------------------
STEP: tearing down the test environment
Panic [0.000 seconds]
[AfterSuite] AfterSuite 
/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:75

  Test Panicked
  runtime error: invalid memory address or nil pointer dereference
  /usr/local/go/src/runtime/panic.go:260

  Full Stack Trace
  sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane.(*APIServer).Stop(0x5c1e90?)
  	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/testing/controlplane/apiserver.go:424 +0x8f
  sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane.(*ControlPlane).Stop(0xc000364780)
  	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/internal/testing/controlplane/plane.go:97 +0x49
  sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Stop(0xc000364780)
  	/home/gibi/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.4/pkg/envtest/server.go:193 +0x114
  github.com/openstack-k8s-operators/ceilometer-operator/controllers.glob..func2()
  	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:77 +0x38
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000506380?)
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xb1
  github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0x0?)
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x125
  github.com/onsi/ginkgo/internal/leafnodes.(*simpleSuiteNode).Run(0xc000155360, 0x43ea16?, 0x0?, {0xc00006ef00?, 0xc0000c3af0?})
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/suite_nodes.go:25 +0x86
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runAfterSuite(0xc000161340)
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:138 +0xce
  github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000161340)
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:71 +0xdd
  github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc00037e1c0, {0x7efc943c8a00, 0xc0001029c0}, {0x1780ec7, 0x10}, {0xc0001629c0, 0x1, 0x1}, {0x19e2300, 0xc00030e480}, ...)
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79 +0x4e5
  github.com/onsi/ginkgo.runSpecsWithCustomReporters({0x19cc120?, 0xc0001029c0}, {0x1780ec7, 0x10}, {0xc000117718, 0x1, 0xf?})
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245 +0x189
  github.com/onsi/ginkgo.RunSpecs({0x19cc120, 0xc0001029c0}, {0x1780ec7, 0x10})
  	/home/gibi/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:220 +0x14a
  github.com/openstack-k8s-operators/ceilometer-operator/controllers.TestAPIs(0x408519?)
  	/home/gibi/upstream/git/openstack-k8s-operators/ceilometer-operator/controllers/suite_test.go:46 +0x45
  testing.tRunner(0xc0001029c0, 0x1863220)
  	/usr/local/go/src/testing/testing.go:1446 +0x10b
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:1493 +0x35f
------------------------------

Ran 0 of 0 Specs in 0.002 seconds
FAIL! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
--- FAIL: TestAPIs (0.00s)
FAIL
FAIL	github.com/openstack-k8s-operators/ceilometer-operator/controllers	0.011s
?   	github.com/openstack-k8s-operators/ceilometer-operator/pkg/ceilometer	[no test files]
FAIL
make: *** [Makefile:279: gotest] Error 1

make-golangci............................................................Passed
make-golint..............................................................Passed
make-generate............................................................Passed
make-kube-linter.........................................................Passed
make-operator-lint.......................................................Passed
bashate..................................................................Passed
```

**Comment by paramite** [comment]
> Hm. I run it locally and only the gotest target fails that I haven't touched and that is passing in the github workflow.

"fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory" means that you don't have kubebuilder initialized. Running "source <(setup-envtest -p env)" should make it pass for you. 

Hmm, the check here fails on your operator-lint job: https://github.com/openstack-k8s-operators/ceilometer-operator/actions/runs/4499305516/jobs/7917002491?pr=57#step:7:35

I've re-run it, so let's see if it passes now.

**Comment by paramite** [comment]
> I've re-run it, so let's see if it passes now.

Failed again ... maybe you have some dependencies installed in your local environment, which GHA environment does not have?

**Comment by gibizer** [comment]
> > Hm. I run it locally and only the gotest target fails that I haven't touched and that is passing in the github workflow.
> 
> "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory" means that you don't have kubebuilder initialized. Running "source <(setup-envtest -p env)" should make it pass for you.

Yeah, I think that should be part of the make target. See example in 
https://github.com/openstack-k8s-operators/nova-operator/blob/70b7e01ff148f10c490b3a20625714994caa2c08/Makefile#L202-L205
https://github.com/openstack-k8s-operators/nova-operator/blob/70b7e01ff148f10c490b3a20625714994caa2c08/Makefile#L127-L129

**Comment by gibizer** [comment]
> > I've re-run it, so let's see if it passes now.
> 
> Failed again ... maybe you have some dependencies installed in your local environment, which GHA environment does not have?
> 
> " - files were modified by this hook"
> 
> also the above ... maybe you need to git commit --amend some changes?

would be nice to see which files :)

**Comment by paramite** [comment]
> would be nice to see which files :)

I had issues recently with CI_TOOLS_REPO when files there were modified unnecessarily. Maybe deleting the directory before the operator-lint (it's not needed anyway for the lint).

**Comment by jlarriba** [comment]
Is this PR still valid and it is something that it should be merged? If that is the case, can someone resolve the merge conflicts?

Thank you!

**Comment by gibizer** [comment]
> Is this PR still valid and it is something that it should be merged? If that is the case, can someone resolve the merge conflicts?
> 
> Thank you!

The goal of the PR is still valid. But I was not able to solve the pre-commit CI issue with the change. I rebased the PR now

**Comment by jlarriba** [comment]
I have tested it and I see what you see Gibi: it works perfectly locally and it does not work on the CI environment. We might be lacking something on the CI. Trying to find out what that might be, I looked at the nova-operator to try to compare environments but I dont see the pre-commit workflow executing there.

Do you have a reference of an operator where this linter is working well in the CI?

**Comment by gibizer** [comment]
Even more strange that it does not work in github action, but it works in the prow job properly https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_telemetry-operator/57/pull-ci-openstack-k8s-operators-telemetry-operator-main-precommit-check/1643613344659148800/artifacts/test/build-log.txt 

I'm wondering, do you want to keep the github action now that prow runs pre-commit as well?

**Comment by jlarriba** [comment]
That's an excellent question, I will come back with an answer.

**Comment by jlarriba** [comment]
We have been discussing this, and we see value to have the operator-lint in the pre-commit action, that is mainly intended to be used by the dev in its local environment. However, it is broke, but it seems that @paramite as already figured out what the problem is and proposed a change: https://github.com/gibizer/ceilometer-operator/pull/1

**Comment by paramite** [comment]
> We have been discussing this, and we see value to have the operator-lint in the pre-commit action, that is mainly intended to be used by the dev in its local environment. However, it is broke, but it seems that @paramite has already figured out what the problem is and proposed a change: [gibizer#1](https://github.com/gibizer/ceilometer-operator/pull/1)

@gibizer ^

**Comment by gibizer** [comment]
Thanks. Let's see if this helps.

**Comment by gibizer** [comment]
> We have been discussing this, and we see value to have the operator-lint in the pre-commit action, that is mainly intended to be used by the dev in its local environment. However, it is broke, but it seems that @paramite has already figured out what the problem is and proposed a change: [gibizer#1](https://github.com/gibizer/ceilometer-operator/pull/1)

Sure, I'm on the side to run operator-lint in pre-commit. There is now a prow job called `ci/prow/precommit-check` that runs the operator-lint as part of pre-commit in CI. Also if you set up pre-commit locally in your repo with `pre-commit install` then operator-lint will be run by pre-commit locally for every git commit. So as far as I see both the local and the CI workflow is covered without the github action `Workflow for pre-commit run / Run pre-commit jobs (pull_request)`. Honestly I run out of ideas why the same pre-commit run behaves differently in the github workflow compared to the local run or the CI run in prow. However I think that the github action is now simply a duplicate that could be removed since both the local and the CI testing is covered without it.

**Comment by gibizer** [comment]
> Thanks. Let's see if this helps.

No it does not.

**Comment by paramite** [comment]
> Honestly I run out of ideas why the same pre-commit run behaves differently in the github workflow compared to the local run or the CI run in prow.

The CI tools exclusion made it show the reason why we have the job failing. IIUC CI environment preparation is changing go modules set [1] hence the pre-commit fails. I'm gonna clone your PR from scratch in VM and reproduce the issue to fix it.

[1] https://github.com/openstack-k8s-operators/telemetry-operator/actions/runs/4698121758/jobs/8330026476?pr=57

**Comment by jlarriba** [comment]
the custom pre-commit has been removed by https://github.com/openstack-k8s-operators/telemetry-operator/pull/82, so now it only executes in prow.

**Comment by gibizer** [comment]
Cool thanks @jlarriba !

**Comment by paramite** [comment]
Sorry for late response, but I figured out the problem here yesterday (reproduced on different PR). The problem is multiple commits. Because pre-commit runs on each of them. If there is problem on first one, it fails and it passws for you locally, because of course you fixed those issues, but most probably amended to last commit like every other sane person ... That's a little process flaw I would say, but it is what it is. Just rebase, squash them and it will pass :).

I still think having this linter running in our pre-commit job (even though we removed it in this repo) is useful.

**Comment by paramite** [comment]
@gibizer @jlarriba ^

**Comment by gibizer** [comment]
Thanks for the explanation @paramite

**Pull request closed without merging**
