### PR TITLE
Remove duplicate proxy image

### PR DESCRIPTION
**Pull request by jlarriba**
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/999

### CODE REVIEW

**Comment by jlarriba** [comment]
recheck

**Comment by vyzigold** [comment]
/retest

Try again after OO update merged.

**Comment by jlarriba** [comment]
Superseded.

**Comment by jlarriba** [comment]
I dont know why the kuttl tests are failing. They work perfectly when running locally, and there is no errors. It seems like it is a matter of timeouts:

`+ oc get deployment openstack-operator-controller-manager
Error from server (NotFound): deployments.apps "openstack-operator-controller-manager" not found`

But it also seems to be happening only on this PR.

**Pull request closed without merging**
