### PR TITLE
[zuul] Add autoscaling job

### PR DESCRIPTION
**Pull request by elfiesmelfie**
This job will deploy openstack with autoscaling components enabled

* Use a pre_deploy hook to create the COO subscription

* Pass kustomization for autoscaling to the tempest job

### CODE REVIEW

**Comment by vyzigold** [comment]
recheck
There were a number of changes being done across the operators to bump the controller-runtime. The CI was expected to fail until that was finished.

**Comment by elfiesmelfie** [comment]
> Build failed (check pipeline). Post `recheck` (without leading slash) to rerun all jobs. Make sure the failure cause has been resolved before you rerun jobs.
> 
> https://review.rdoproject.org/zuul/buildset/0e252f3f17444cfaa8da4c74164f1750
> 
> ✔️ [openstack-k8s-operators-content-provider ](https://review.rdoproject.org/zuul/build/339b28e4d4c142f59497b0f0f91d55a3) SUCCESS in 1h 15m 26s ✔️ [podified-multinode-edpm-deployment-crc ](https://review.rdoproject.org/zuul/build/527ef2e387164d9bb388918b5f6d6267) SUCCESS in 52m 15s ❌ [telemetry-operator-multinode-autoscaling ](https://review.rdoproject.org/zuul/build/75078a4bc4f14ca0b0c37a68d60d346e) **FAILURE** in 58m 38s

https://logserver.rdoproject.org/01/301/c5780491a891c186062df36de387bd8d40633ab8/github-check/telemetry-operator-multinode-autoscaling/75078a4/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack-operators/all_resources.log
The errors seems to be due to the baremetal operator crashlooping:

pod/openstack-baremetal-operator-controller-manager-657fc9cb4cgrj8g   1/2     CrashLoopBackOff   8 (44s ago)   34m

**Comment by elfiesmelfie** [comment]
check-rdo

The failure is unrelated to this change. I can't find any errors in telemetry components.
If I keep seeing issues with the baremetal operator, I'll disable it, since it is not used in the test environment because we're using pre-provisioned nodes

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
check-rdo

**Review by jlarriba — APPROVED** [review]
We will need to also create a subscription to CLO to be able to deploy and test the logging integration, but that would be subject of a new PR. This lgtm

**Pull request merged**
