### PR TITLE
update finalzier to CRD doc

### PR DESCRIPTION
**Pull request by stuggi**
Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/519
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/231

### CODE REVIEW

**Comment by stuggi** [comment]
recheck

**Comment by bshephar** [comment]
https://review.rdoproject.org/zuul/build/5dfbadadb79940519482305c5dd47357
```
❯ curl -s https://logserver.rdoproject.org/14/414/d70a41985e039c8afc8080a0675fa5a5df940922/github-check/podified-multinode-edpm-deployment-crc/5dfbada/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/openstackcontrolplanes.core.openstack.org/openstack-galera-network-isolation.yaml | yq ".status.conditions[0] | select(.status == "False")"
lastTransitionTime: "2024-06-19T18:05:33Z"
message: OpenStackControlPlane Glance in progress
reason: Requested
severity: Info
status: "False"
type: Ready
```

**Comment by bshephar** [comment]
recheck

**Pull request merged**
