### PR TITLE
Add RabbitMQ dashboard

### PR DESCRIPTION
**Pull request by vyzigold**
I attempted to re-create a similar dashboard to the one on the RabbitMQ website. https://www.rabbitmq.com/docs/prometheus

pic-sel-240619-0940-56

pic-sel-240619-0941-11

pic-sel-240619-0941-22

pic-sel-240619-0941-43

pic-sel-240619-0942-02

pic-sel-240619-0942-13

pic-sel-240619-0942-23

pic-sel-240619-0942-31

### CODE REVIEW

**Comment by vyzigold** [comment]
```
 go binary does not contain required 'symbol(s)
```
Known issue across all of the operators. People are already looking into it.

**Comment by vyzigold** [comment]
recheck

**Review by csibbitt — APPROVED** [review]
The code looks good. I didn't load the dashboard to inspect it, but I did briefly review all the queries ("expr" fields in the dashboard) and confirmed that they look sane to me, match the title of the panel, and that rate() is used for `/s` metrics.

**Comment by vyzigold** [comment]
I rebased on top of main and resolved merge conflicts.

**Pull request merged**
