### PR TITLE
Adding a Ceilometer-based VM dashboard

### PR DESCRIPTION
**Pull request by csibbitt**

### CODE REVIEW

**Comment by csibbitt** [comment]
I put this up for review now that it's working, but I'm going to try adding some recording rules to eliminate the repetitive `label_replace` syntax in all the queries, as well as see if I can get it to have VM names instead of IDs in the drop down selector.

Here's a current screenshot

image

As you can see the units are also messed up. Setting them correctly in Grafana (before exporting it) doesn't seem to help, so some more experimentation in the console UI definitions is necessary to see if I can get that sorted; otherwise additional recording rules may be required.

**Comment by csibbitt** [comment]
Kuttl tests are passing locally. I want to test this with a multi-CPU VM to see what it looks like, but this version is good enough to review, and probably to merge unless an error is spotted.

**Comment by csibbitt** [comment]
Kuttl tests are passing locally. I want to test this with a multi-CPU VM to see what it looks like, but this version is good enough to review, and probably to merge unless an error is spotted.

**Comment by jlarriba** [comment]
Kuttl tests are failing due to an issue introduced in Heat that will be solved by  https://github.com/openstack-k8s-operators/heat-operator/pull/344

**Comment by jlarriba** [comment]
recheck

Seems to be an unrelated issue with Keystone:

`2024-04-03T02:47:11Z	ERROR	controller-runtime.source.EventHandler	failed to get informer from cache	{"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: keystone.openstack.org/v1beta1: the server could not find the requested resource"}`

**Comment by vyzigold** [comment]
There still seems to be the "heat not ready" issue. What's worrying me though is this in the ceilometer-central-agent pod:
```
2024-04-03 11:08:27.297 14 WARNING keystoneauth.discover [-] Failed to contact the endpoint at https://keystone-public-openstack.apps-crc.testing for discovery. Fallback to using that endpoint as the base url.
2024-04-03 11:08:27.349 14 ERROR ceilometer.polling.manager [-] Skipping tenant, keystone issue: SSL exception connecting to https://keystone-public-openstack.apps-crc.testing/domains?: HTTPSConnectionPool(host='keystone-public-openstack.apps-crc.testing', port=443): Max retries exceeded with url: /domains (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)'))): keystoneauth1.exceptions.connection.SSLError: SSL exception connecting to https://keystone-public-openstack.apps-crc.testing/domains?: HTTPSConnectionPool(host='keystone-public-openstack.apps-crc.testing', port=443): Max retries exceeded with url: /domains (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1129)')))
2024-04-03 11:08:27.359 14 DEBUG ceilometer.polling.manager [-] Skip pollster storage.objects.containers, no  resources found this cycle poll_and_notify /usr/lib/python3.9/site-packages/ceilometer/polling/manager.py:193
```

It's expected and correct to fail with ssl error with the current configuration when connecting to public keystone endpoint. There is no CA cert in ceilometer pod. But why does it try to connect to the public keystone endpoint? There isn't any mention of it in the ceilometer config. And I'm pretty sure it had to use internal endpoint before, because the public one is behind TLS for months now, so we would see an error earlier.

**Comment by jlarriba** [comment]
I think this is what is causing the issue: https://github.com/openstack-k8s-operators/telemetry-operator/blob/main/controllers/ceilometer_controller.go#L928.

But I dont know why, it should be connecting via the internal keystone endpoint too, as that cannot be chosen: https://github.com/openstack-k8s-operators/keystone-operator/blob/e5f862707f49c367a1486e928eb7ad0663408f45/api/v1beta1/keystoneapi.go#L79

**Comment by vyzigold** [comment]
This is executed by the operator, while the logs come from the ceilometer-agent-notification container.

**Comment by csibbitt** [comment]
I tested a multi-CPU VM and it looks like ceilometer_cpu metric already aggregates across the VCPUs as there was only one metric for the VM. Therefore all is good; not additional aggregation or handling is required AFAICT.

**Comment by jlarriba** [comment]
I was wrong yesterday, the Swift changes have nothing to do, as the errors are in Ceilometer itself, not in the operator's controller. Suddendly, all PRs started hitting this issue and are trying to connect to public keystone.

**Comment by jlarriba** [comment]
retest

**Comment by jlarriba** [comment]
recheck

**Comment by jlarriba** [comment]
recheck

**Comment by csibbitt** [comment]
EDPM test failed at "Wait until the test-operator csv is present"

**Comment by csibbitt** [comment]
recheck

**Pull request merged**
