### PR TITLE
Refactor dashboard related creation into its own method

### PR DESCRIPTION
**Pull request by csibbitt**
No real changes, just a minor refactor because reconcileNormal() is getting huge

### CODE REVIEW

**Comment by csibbitt** [comment]
Looks like a problem on the registry side `time="2024-06-11T14:17:04Z" level=fatal msg="initializing source docker://quay.io/openstack-k8s-operators/dataplane-operator-bundle:319ec0e5a28b98fbdb10f3861cb0c6c98e0c96ae: Requesting bearer token: invalid status code from registry 502 (Bad Gateway)"`

**Comment by jlarriba** [comment]
There is a kuttl error:

`case.go:364: failed in step 1-deploy
 case.go:366: uiplugins.observability.openshift.io "dashboards" not found`

**Comment by csibbitt** [comment]
Thank you kuttle! This is a discrepancy on L487 vs L544 because this was created at the same time as the name change (I tested locally with this rebased onto that). Fix coming momentarily.

**Comment by jlarriba** [comment]
recheck

**Comment by vyzigold** [comment]
recheck

**Comment by vyzigold** [comment]
/test telemetry-operator-build-deploy-kuttl
kuttl failed because of a known and already fixed issue:
```
go binary does not contain required 'symbol(s)'
```

**Pull request merged**
