### PR TITLE
Cleanup golangci-lint

### PR DESCRIPTION
**Pull request by gibizer**
Since the controller runtime and golang bump the golangci-lint github action started to fail. However golangci-lint (and the rest of the linters) also run in pre-commit both locally and in CI. So the github action is removed. Also I took the opportunity to bump the golangci-lint version to the newest that still supports 1.20. And removed disabled checks that passing now.

### CODE REVIEW

**Review by jlarriba — APPROVED** [review]

**Comment by gibizer** [comment]
Seems we need mariadbaccount RBAC change. The newer mariadb-operator pulled in by the controller-runtime bump has the MariaDBAccount in place already.

```
0215 17:16:10.036455       1 reflector.go:535] go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1beta1.MariaDBAccount: mariadbaccounts.mariadb.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "mariadbaccounts" in API group "mariadb.openstack.org" at the cluster scope
E0215 17:16:10.036485       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1beta1.MariaDBAccount: failed to list *v1beta1.MariaDBAccount: mariadbaccounts.mariadb.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "mariadbaccounts" in API group "mariadb.openstack.org" at the cluster scope
W0215 17:16:42.861163       1 reflector.go:535] go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1beta1.MariaDBAccount: mariadbaccounts.mariadb.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "mariadbaccounts" in API group "mariadb.openstack.org" at the cluster scope
E0215 17:16:42.861196       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1beta1.MariaDBAccount: failed to list *v1beta1.MariaDBAccount: mariadbaccounts.mariadb.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "mariadbaccounts" in API group "mariadb.openstack.org" at the cluster scope
W0215 17:17:30.417636       1 reflector.go:535] go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: failed to list *v1beta1.MariaDBAccount: mariadbaccounts.mariadb.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "mariadbaccounts" in API group "mariadb.openstack.org" at the cluster scope
E0215 17:17:30.417767       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.28.3/tools/cache/reflector.go:229: Failed to watch *v1beta1.MariaDBAccount: failed to list *v1beta1.MariaDBAccount: mariadbaccounts.mariadb.openstack.org is forbidden: User "system:serviceaccount:openstack-operators:telemetry-operator-controller-manager" cannot list resource "mariadbaccounts" in API group "mariadb.openstack.org" at the cluster scope
```

However I'm not sure this is the only issue as I see also
```
2024-02-15T17:05:20Z	ERROR	Reconciler error	{"controller": "telemetry", "controllerGroup": "telemetry.openstack.org", "controllerKind": "Telemetry", "Telemetry": {"name":"telemetry-kuttl","namespace":"telemetry-kuttl-tests"}, "namespace": "telemetry-kuttl-tests", "name": "telemetry-kuttl", "reconcileID": "c54c839f-acf9-43d7-bb04-497023968063", "error": "MetricStorage.telemetry.openstack.org \"metric-storage\" is invalid: spec.monitoringStack.dataplaneNetwork: Invalid value: \"\": spec.monitoringStack.dataplaneNetwork in body should match '^[a-zA-Z0-9][a-zA-Z0-9\\-_]*[a-zA-Z0-9]$'"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/controller/controller.go:227
```
in the operator log during the kuttl test

**Comment by gibizer** [comment]
recheck retry limit

**Comment by gibizer** [comment]
/test telemetry-operator-build-deploy
unrelated
```
+ oc new-build --binary --strategy=docker --name telemetry-operator-index --to=docker.io/rdotripleomirror/telemetry-operator-index:2fddfbff52445136cba6-1758423373056053248 --push-secret=push-quay-secret --to-docker=true
    * A Docker build using binary input will be created
      * The resulting image will be pushed with Docker to "docker.io/rdotripleomirror/telemetry-operator-index:2fddfbff52445136cba6-1758423373056053248"
      * A binary build was created, use 'oc start-build --from-dir' to trigger a new build

--> Creating resources with label build=telemetry-operator-index ...
    error: Internal error occurred: resource quota evaluation timed out
--> Failed
```

**Comment by jlarriba** [comment]
@vyzigold There is an error with the MariaDBDatabase, could you please assist with this debug?

2024-02-16T10:15:01Z	ERROR	Reconciler error	{"controller": "autoscaling", "controllerGroup": "telemetry.openstack.org", "controllerKind": "Autoscaling", "Autoscaling": {"name":"telemetry-kuttl","namespace":"telemetry-kuttl-tests"}, "namespace": "telemetry-kuttl-tests", "name": "telemetry-kuttl", "reconcileID": "eb6ff792-3107-415d-a4d4-29a5107687c9", "error": "Error create or update DB object aodh *v1beta1.MariaDBDatabase telemetry-kuttl-tests/aodh: Object telemetry-kuttl-tests/aodh is already owned by another Autoscaling controller autoscaling"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.4/pkg/internal/controller/controller.go:227

**Pull request merged**
