### PR TITLE
Re-init conditions each reconcile

### PR DESCRIPTION
**Pull request by fmount**
This patch follows the same pattern applied to the other operators, where we re-init the `conditions` at each reconcile loop. `Conditions` are re-evaluated and updated, keeping the `LastTransitionTime` for those that haven't changed (it avoids the transition from `True` to `Unknown` to `True` again).
In addition, the `observedGeneration` field is introduced, and it is used by the `openstack-operator` to check the `IsReady()` function for a particular `CR` in case a minor update is triggered. All the conditions are evaluated during the main `Reconcile` loop ( or the `reconcileNormal` function in some circumstances), hence the main `ReadyCondition` is updated within the same flow. The defer function still updates the `Resource` and `Mirror` the condition to the top-level `CR`.

Depends-On: https://github.com/openstack-k8s-operators/heat-operator/pull/344
Jira: [OSPRH-5919](https://issues.redhat.com//browse/OSPRH-5919)
Jira: [OSPRH-5698](https://issues.redhat.com/browse/OSPRH-5698)

### CODE REVIEW

**Comment by vyzigold** [comment]
The CI didn't finish, because heat never achieved Ready state (autoscaling isn't ready, but it's in fact just waiting for heat). The conditions in heat cfnapi behave strangely - everything is ready, but the main condition says "Unknown". Couldn't that be related to a similar PR like this in heat? https://logserver.rdoproject.org/59/359/3688bb5a5a27a3cd2829825ee2e2e02f4a8c59b4/github-check/telemetry-operator-multinode-autoscaling-tempest/ff6bf1a/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/heatcfnapis.heat.openstack.org/heat-cfnapi.yaml

**Comment by fmount** [comment]
> The CI didn't finish, because heat never achieved Ready state (autoscaling isn't ready, but it's in fact just waiting for heat). The conditions in heat cfnapi behave strangely - everything is ready, but the main condition says "Unknown". Couldn't that be related to a similar PR like this in heat? https://logserver.rdoproject.org/59/359/3688bb5a5a27a3cd2829825ee2e2e02f4a8c59b4/github-check/telemetry-operator-multinode-autoscaling-tempest/ff6bf1a/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/heatcfnapis.heat.openstack.org/heat-cfnapi.yaml

Thank you, it makes sense, and it should be fixed by: https://github.com/openstack-k8s-operators/heat-operator/pull/344

**Comment by jlarriba** [comment]
Actually, that will solve the Kuttl issue on ALL of our PRs ;)

Thank you Francesco and Jaromir!

**Comment by jlarriba** [comment]
recheck

The Zuul jobs are not affected by this issue so they can pass

**Comment by dprince** [comment]
looks good to me

**Review by jlarriba — APPROVED** [review]

**Review by dprince — APPROVED** [review]

**Pull request merged**
