### PR TITLE
Use conditional assignment for BRANCH

### PR DESCRIPTION
**Pull request by stuggi**
depends-on: https://github.com/openstack-k8s-operators/install_yamls/pull/975

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by vyzigold** [comment]
recheck - we have operators restarting (not only telemetry-operator, openstack-operator restarted too) I believe last time this was caused by lack of resources in the CI, so it's unrelated to the PR:
```
E1203 17:11:15.981696       1 reflector.go:147] go/pkg/mod/k8s.io/client-go@v0.29.11/tools/cache/reflector.go:229: Failed to watch *v1alpha1.ImageContentSourcePolicy: unknown (get imagecontentsourcepolicies.operator.openshift.io)
E1203 17:11:17.481782       1 leaderelection.go:369] Failed to update lock: Operation cannot be fulfilled on leases.coordination.k8s.io "40ba705e.openstack.org": the object has been modified; please apply your changes to the latest version and try again
I1203 17:11:19.201042       1 leaderelection.go:285] failed to renew lease openstack-operators/40ba705e.openstack.org: timed out waiting for the condition
```

**Comment by stuggi** [comment]
rebased, should fix the pre-commit issue

**Comment by vyzigold** [comment]
/retest
See if the failure is consistent.

Kuttl tests failed because of infra operator:
```
logger.go:42: 09:23:44 | tests/5-prepare-for-edpm-power-mon | Error from server (InternalError): error when creating "../deps/dnsmasq.yaml": Internal error occurred: failed calling webhook "mdnsmasq.kb.io": failed to call webhook: Post "[https://infra-operator-controller-manager-service.openstack-operators.svc:443/mutate-network-openstack-org-v1beta1-dnsmasq?timeout=10s](https://infra-operator-controller-manager-service.openstack-operators.svc/mutate-network-openstack-org-v1beta1-dnsmasq?timeout=10s)": no endpoints available for service "infra-operator-controller-manager-service"
```
Infra operator failed with:
```
2024-12-13T09:35:18Z	ERROR	setup	problem running manager	{"error": "failed to wait for bgpconfiguration caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.FRRConfiguration"}
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_telemetry-operator/554/pull-ci-openstack-k8s-operators-telemetry-operator-main-telemetry-operator-build-deploy-kuttl/1867480018716725248/artifacts/telemetry-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-3d1f620ae3617fbd6371f55aa948b34e9daf31a461d3c557cf1a7c2db38d0385/namespaces/openstack-operators/pods/infra-operator-controller-manager-8648dc6988-qjjxd/logs/manager-previous.log

**Comment by stuggi** [comment]
added depends-on for https://github.com/openstack-k8s-operators/install_yamls/pull/975 , but not sure if that will work. lets see

**Comment by stuggi** [comment]
pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": dial tcp 38.129.56.158:443: i/o timeout

**Comment by stuggi** [comment]
pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": dial tcp 38.129.56.158:443: i/o timeout

**Pull request merged**
