### PR TITLE
Instead of uuids, list out node hostnames in Kepler dashboard

### PR DESCRIPTION
**Pull request by yadneshk**
Update all queries to use hostname label instead.

### CODE REVIEW

**Comment by jlarriba** [comment]
With node_exporter we are using fqdn now (https://github.com/openstack-k8s-operators/telemetry-operator/pull/535). Please, rebase on top of main and use fqdn instead of hostname for the Label to keep everything in sync.

**Comment by yadneshk** [comment]
hostname

**Comment by yadneshk** [comment]
Wait for https://github.com/openstack-k8s-operators/telemetry-operator/pull/543 to merge first

**Pull request merged**
