### PR TITLE
[go.mod]Bump from v0.3.0 to pseudoversion

### PR DESCRIPTION
**Pull request by gibizer**
Our intention is to track service operator and lib-common dependencies via pseudoversions. However renovate does not automatically bump from a tagged version (e.g. v0.3.0) to a newer but not tagged pseudoversion. So this patch does the manual bump. After this renovate will bump the newer pseduoversions.

### CODE REVIEW

**Comment by jlarriba** [comment]
Let's see how this one goes.

**Comment by gibizer** [comment]
/test telemetry-operator-build-deploy-kuttl
```

+ cat
oc apply -f /alabama/install_yamls/out/openstack/namespace.yaml
namespace/openstack created
timeout 300s bash -c "while ! (oc get project openstack); do sleep 1; done"
Error from server (NotFound): projects.config.openshift.io "openstack" not found
```

**Comment by jlarriba** [comment]
Strange, it actually seemed to be that you were creating the PR from "ceilometer-operator" dir. Now everything is passing correctly.

**Comment by gibizer** [comment]
> Strange, it actually seemed to be that you were creating the PR from "ceilometer-operator" dir. Now everything is passing correctly.

strange indeed.

**Pull request merged**
