### PR TITLE
bump to golang 1.21 and k8s to 1.29

### PR DESCRIPTION
**Pull request by stuggi**
Jira: https://issues.redhat.com//browse/OSPRH-6501

### CODE REVIEW

**Review by dprince — APPROVED** [review]

**Comment by stuggi** [comment]
the build src-amd64 failed after 1m40s with reason OutOfMemoryKilled: The build pod was killed due to an out of memory condition.

**Comment by jlarriba** [comment]
It seems that the current error has something to do with the change of versions, as it seems to be complaining about the go binary:

```
or:ErrLibcryptoMissing' 'Files:[/usr/bin/runc]' 'Dirs:[]' 'Tags:[]}]}' 'skopeo:{FilterFiles:[]' 'FilterDirs:[]' 'ErrIgnores:[{Error:ErrGoMissingTag' 'Files:[/usr/bin/skopeo]' 'Dirs:[]' 'Tags:[]}]}' 'tini:{FilterFiles:[]' 'FilterDirs:[]' 'ErrIgnores:[{Error:ErrNotDynLinked' 'Files:[/usr/bin/tini-static]' 'Dirs:[]' 'Tags:[]}]}]' 'ErrIgnores:[]}}' I0925 06:51:20.248272 1 'main.go:103]' '"scan"' 'version="0.3.1-181-g5ca3adc5-dirty"' I0925 06:51:24.412800 1 'scan.go:460]' '"scanning' 'failed"' 'image="docker.io/rdotripleomirror/telemetry-operator:60ee4d973021487edc98-1838825064997326848"' 'path="/manager"' 'error="go' binary does not contain required 'symbol(s)"' 'component="telemetry-operator-container"' 'tag=""' 'rpm=""' 'status="failed"' ---- Failure Report +------------------------------+-----------------+-----------------------------------------------+----------------------------------------------------------------------------------------+ '|' OPERATOR NAME '|' EXECUTABLE NAME '|' STATUS '|' IMAGE '|' +------------------------------+-----------------+-----------------------------------------------+----------------------------------------------------------------------------------------+ '|' telemetry-operator-container '|' /manager '|' go binary does not contain required 'symbol(s)' '|' docker.io/rdotripleomirror/telemetry-operator:60ee4d973021487edc98-1838825064997326848 '|' +------------------------------+-----------------+-----------------------------------------------+----------------------------------------------------------------------------------------+ F0925 06:51:24.849322 1 'main.go:296]' Error: run failed
```

**Comment by stuggi** [comment]
the fips check fails for some reason. 

```
+ REPORT_OUT='Trying to pull registry.ci.openshift.org/ci/check-payload:latest...
Getting image source signatures
Copying blob sha256:18da7a9c57059dd9c77c357821b2f2124eac8f2171f73b685c24d0315a0daea2
```

but it was successful for e.g. the swift operator using the same check-payload image:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openstack-k8s-operators_swift-operator/273/pull-ci-openstack-k8s-operators-swift-operator-main-swift-operator-build-deploy-kuttl/1838820160530550784/artifacts/swift-operator-build-deploy-kuttl/openstack-k8s-operators-fips-check/build-log.txt

```
+ REPORT_OUT='Trying to pull registry.ci.openshift.org/ci/check-payload:latest...
Getting image source signatures
Copying blob sha256:18da7a9c57059dd9c77c357821b2f2124eac8f2171f73b685c24d0315a0daea2
Copying blob sha256:9f5e869c2e09cebe2db12b2508929db77952868434757d146f3935bc87ec806e
Copying blob sha256:ca1636478fe5b8e2a56600e24d6759147feb15020824334f4a798c1cb6ed58e2
Copying blob sha256:7fc4e2f1866bfbc02dec2637b27c4d461476e8abb5e1d73ab78bca96e70c480d
Copying blob sha256:50458fe276b7d82f425e0a0e776dab659cad4dc0ae16e2d48a8b56acfe3b2e1c
Copying config sha256:66c75ee79457e7be84894d6672935d3e9f51b5a3ba40a708cb7faa8ebc0e37ae
Writing manifest to image destination
I0925 06:21:11.147014       1 main.go:315] using embedded config
I0925 06:21:11.149380       1 types_config.go:12] using config &{Components:[] FailOnWarnings:false FilterFile: FromFile: FromURL: InsecurePull:false Limit:-1 ContainerImageComponent: ContainerImage: OutputFile: OutputFormat:table Parallelism:5 Java:false PrintExceptions:false PullSecret: TimeLimit:1h0m0s Verbose:false UseRPMScan:false ConfigFile:{FilterFiles:[] FilterDirs:[/lib/firmware /lib/modules /usr/lib/.build-id /usr/lib/firmware /usr/lib/grub /usr/lib/modules /usr/share/app-info /usr/share/doc /usr/share/fonts /usr/share/icons /usr/share/openshift /usr/src/plugins /rootfs /sysroot] FilterImages:[] JavaDisabledAlgorithms:[DH keySize < 2048 TLSv1.1 TLSv1 SSLv3 SSLv2 TLS_RSA_WITH_AES_256_CBC_SHA256 TLS_RSA_WITH_AES_256_CBC_SHA TLS_RSA_WITH_AES_128_CBC_SHA256 TLS_RSA_WITH_AES_128_CBC_SHA TLS_RSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_AES_128_GCM_SHA256 DHE_DSS RSA_EXPORT DHE_DSS_EXPORT DHE_RSA_EXPORT DH_DSS_EXPORT DH_RSA_EXPORT DH_anon ECDH_anon DH_RSA DH_DSS ECDH 3DES_EDE_CBC DES_CBC RC4_40 RC4_128 DES40_CBC RC2 HmacMD5] CertifiedDistributions:[] PayloadIgnores:map[openshift-enterprise-pod-container:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrNotDynLinked Files:[/usr/bin/pod] Dirs:[] Tags:[]}]} openshift-istio-cni-rhel8-container:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrLibcryptoSoMissing Files:[/opt/cni/bin/istio-cni-rhel9] Dirs:[] Tags:[]}]} openshift-virtualization-cdi-container:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoNotCgoEnabled Files:[/usr/bin/cdi-containerimage-server] Dirs:[] Tags:[]}]} openshift-virtualization-virt-container:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrNotDynLinked Files:[/usr/bin/container-disk] Dirs:[] Tags:[]}]}] TagIgnores:map[] RPMIgnores:map[containernetworking-plugins:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoMissingTag Files:[] Dirs:[/usr/libexec/cni] Tags:[]}]} cri-o:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoMissingTag Files:[/usr/bin/crio /usr/bin/crio-status] Dirs:[] Tags:[]} {Error:ErrNotDynLinked Files:[/usr/bin/pinns] Dirs:[] Tags:[]}]} cri-tools:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoMissingTag Files:[/usr/bin/crictl] Dirs:[] Tags:[]}]} glibc:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrNotDynLinked Files:[/usr/sbin/ldconfig /sbin/ldconfig] Dirs:[] Tags:[]}]} glibc-common:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrNotDynLinked Files:[/usr/sbin/build-locale-archive] Dirs:[] Tags:[]}]} ignition:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoMissingTag Files:[/usr/lib/dracut/modules.d/30ignition/ignition] Dirs:[] Tags:[]}]} podman:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoMissingTag Files:[/usr/bin/podman /usr/libexec/podman/quadlet /usr/libexec/podman/rootlessport] Dirs:[] Tags:[]} {Error:ErrNotDynLinked Files:[/usr/libexec/podman/catatonit] Dirs:[] Tags:[]}]} podman-catatonit:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrNotDynLinked Files:[/usr/libexec/catatonit/catatonit] Dirs:[] Tags:[]}]} runc:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoMissingTag Files:[/usr/bin/runc] Dirs:[] Tags:[]} {Error:ErrGoInvalidTag Files:[/usr/bin/runc] Dirs:[] Tags:[]} {Error:ErrGoMissingSymbols Files:[/usr/bin/runc] Dirs:[] Tags:[]} {Error:ErrLibcryptoMissing Files:[/usr/bin/runc] Dirs:[] Tags:[]}]} skopeo:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrGoMissingTag Files:[/usr/bin/skopeo] Dirs:[] Tags:[]}]} tini:{FilterFiles:[] FilterDirs:[] ErrIgnores:[{Error:ErrNotDynLinked Files:[/usr/bin/tini-static] Dirs:[] Tags:[]}]}] ErrIgnores:[]}}
```

I'll rerun just to see if it is permanent issue

**Comment by stuggi** [comment]
issue is in the check-payload scanner which fails after the latest go-toolset which bumped golang to 1.21.13 . with the previous version (1.21.10) it was successful and used for the successful PRs in the other service operators. we now start to see it there, too on new PRs. we track it here https://issues.redhat.com/browse/OSPRH-10362

**Pull request merged**
