### PR TITLE
[zuul] Add a job to test WIP branches in telemetry-tempest-plugin

### PR DESCRIPTION
**Pull request by elfiesmelfie**
https://review.opendev.org/c/openstack/telemetry-tempest-plugin/+/909856
Related to https://review.rdoproject.org/r/c/config/+/52007

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
check-rdo

**Comment by mgirgisf** [comment]
you will need to add openstack-k8s-operators-content-provider as you mentioned but take care after the update in rdo you will need to 
    override-checkout: main

**Comment by elfiesmelfie** [comment]
> Unable to freeze job graph: Job telemetry-operator-check-telemetry-tempest-master depends on openstack-k8s-operators-content-provider which was not run.

This is because I didn't add the content provider to the template, and didn't configure it to run anywhere. The telemetry-operator-* jobs depend on the content provider to provided the container images

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
recheck

**Comment by elfiesmelfie** [comment]
> Build failed (check pipeline). Post `recheck` (without leading slash) to rerun all jobs. Make sure the failure cause has been resolved before you rerun jobs.
> 
> https://review.rdoproject.org/zuul/buildset/52e7cf8c502147b4880d035c9e18e313
> 
> ✔️ [openstack-k8s-operators-content-provider ](https://review.rdoproject.org/zuul/build/f77f2491472d4a9db795af5543194b8c) SUCCESS in 1h 32m 15s ✔️ [podified-multinode-edpm-deployment-crc ](https://review.rdoproject.org/zuul/build/6673ff2b262c4868ae50e7cef6abc7a5) SUCCESS in 1h 08m 30s ❌ [telemetry-operator-check-telemetry-tempest-master ](https://review.rdoproject.org/zuul/build/0c998bb2cdc64fb4b22e25307612aba3) **FAILURE** in 1h 02m 10s

This failure is not related to this change. It is caused by a tempest test failure.
I checked the tempest_pod_output and it showed that there was no external plugin set.
grep -i "external" -> indicates nothing was passed in
grep -i "pip" -> nothing was installed

This is a success! (for no depends-on) i.e. regular PR to this repo (or any repo).

I'm going to re-add the depends on and see does that work as expected i.e. install from the review branch and run tests from a patch.

**Comment by elfiesmelfie** [comment]
recheck

**Pull request merged**
