### PR TITLE
[OSPRH-9848] enhance NodeExporter metrics

### PR DESCRIPTION
**Pull request by vyzigold**
This adds a "hostname" label to NodeExporter metrics
to make the identification of the node of origin a little easier
than just having the IP address.

As a side effect of needing a little different parsing for
NodeExporter and Kepler ScrapeConfigs, the code to get compute
node IPs from ansible facts and from IPsets is now executed
only once (in comparison to executing it twice), which greatly
reduces k8s api calls.

### CODE REVIEW

**Comment by vyzigold** [comment]
An example from my environment. (before the PR, there wouldn't be the "hostname" label): 
pic-sel-241112-2344-55

**Comment by jlarriba** [comment]
We identified at the same time that having that label is very useful for all metrics coming for the VMs, thats why we have started working on a Ceilometer Compute modification to include it: https://issues.redhat.com/browse/OSPRH-11406

**Comment by vyzigold** [comment]
Cool, I didn't know that. An update to this. I chatted with Yadnesh and Kepler is expected to include this label on its own, so I'll be reworking the code throughout the day to affect only Node Exporter metrics.

**Comment by vyzigold** [comment]
This can be seen working in the CI. The new ScrapeConfig for NodeExporter can be seen here: https://logserver.rdoproject.org/27/527/5130e45b6230032820ce2a9dc211e19ce8d85f93/github-check/functional-metric-verification-tests-osp18/06c8093/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/crs/scrapeconfigs.monitoring.rhobs/telemetry-node-exporter-tls.yaml

We can see, that scraping of ceilometer, node exporter and rabbitmq still works thanks to the metric-verification job: https://logserver.rdoproject.org/27/527/5130e45b6230032820ce2a9dc211e19ce8d85f93/github-check/functional-metric-verification-tests-osp18/06c8093/controller/ci-framework-data/logs/feature-verification-tests/summary_result.log

**Pull request merged**
