### PR TITLE
Moved the constants to a telemetry-wide file for bettery readability

### PR DESCRIPTION
**Pull request by jlarriba**

### CODE REVIEW

**Comment by jlarriba** [comment]
recheck

**Comment by jlarriba** [comment]
recheck

**Comment by vyzigold** [comment]
recheck
```
tempest.exceptions.BuildErrorException: Server a88ce08c-3fb8-4cb5-9326-706837dc79b1 failed to build and is in ERROR status
Details:  Request ID of server operation performed before checking the server status req-1bd98f29-9f10-4d64-9a5f-c1c281c8002f.
```

**Comment by vyzigold** [comment]
recheck
The same unrelated error again
```
tempest.exceptions.BuildErrorException: Server c93d8916-8cd0-4005-be5d-cf6b7072eb52 failed to build and is in ERROR status
Details:  Request ID of server operation performed before checking the server status req-cae4aa51-946d-4b4a-89c2-a05d15c5de09.
```

**Comment by vyzigold** [comment]
recheck
A race condition between keystone and ceilometer this time:
```
2024-03-28 11:37:22.408 14 ERROR ceilometer.polling.manager [-] Skipping images, keystone issue: internalURL endpoint for image service not found: keystoneauth1.exceptions.catalog.EndpointNotFound: internalURL endpoint for image service not found
2024-03-28 11:37:22.408 14 DEBUG ceilometer.polling.manager [-] Skip pollster image.size, no  resources found this cycle poll_and_notify /usr/lib/python3.9/site-packages/ceilometer/polling/manager.py:193
```

**Pull request merged**
