### PR TITLE
[OSPRH-8076] Fix CustomMonitoringStack

### PR DESCRIPTION
**Pull request by vyzigold**
The CRD fields "DataplaneNetwork" and "DashboardsEnabled" should be usable by all MetricStorages, so they should be in the MetricStorageSpec instead of being inside the "MonitoringStack".

As the DataplaneNetwork field is required, this fixes the CustomMonitoringStack. I also added some more kuttl tests to test deploying the CustomMonitoringStack.

### CODE REVIEW

**Comment by vyzigold** [comment]
CI failed with:
```
 STEP 1/8: FROM image-registry.openshift-image-registry.svc:5000/ci-op-cin6k97i/pipeline@sha256:67d1a0878fc1d5a8c3f1ba1bdea94b7eca3ba49c81014775cc15c66e84d8c065
Trying to pull image-registry.openshift-image-registry.svc:5000/ci-op-cin6k97i/pipeline@sha256:67d1a0878fc1d5a8c3f1ba1bdea94b7eca3ba49c81014775cc15c66e84d8c065...
INFO[2024-07-02T08:09:45Z] Ran for 58s                                  
ERRO[2024-07-02T08:09:45Z] Some steps failed:                           
ERRO[2024-07-02T08:09:45Z] 
  * could not run steps: step src failed: error occurred handling build src-amd64: the build src-amd64 failed after 58s with reason DockerBuildFailed: Dockerfile build strategy has failed. 
```
I don't think that's connected to the PR, I'll wait some time before trying again.

**Comment by jlarriba** [comment]
Here: https://github.com/openstack-k8s-operators/telemetry-operator/pull/423, I also see those two tests failing. I have been looking but it seems to be related to something else.

**Comment by vyzigold** [comment]
recheck

**Comment by vyzigold** [comment]
Thanks to the kuttl test I noticed you can't remove the MonitoringStack or CustomMonitoringStack part of MetricStorage from the telemetry CR. I fixed that in the second commit.

**Comment by vyzigold** [comment]
/retest
Github is still waiting for kuttl test results after 4 days.

**Pull request merged**
