### PR TITLE
[zuul][tempest] Re-enable the sg_core integration test

### PR DESCRIPTION
**Pull request by elfiesmelfie**
Depends-On: https://review.opendev.org/c/openstack/telemetry-tempest-plugin/+/909459
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/284

### CODE REVIEW

**Comment by elfiesmelfie** [comment]
Once this passes, we can merge it into the main PR for the tempest job.

**Comment by elfiesmelfie** [comment]
check-rdo

**Comment by vyzigold** [comment]
The opendev patch is merged in master now. I resolved the merge conflict, that was here and zuul is pointing to master now. If this passes CI, then I think we can merge this.

**Pull request merged**
