### PR TITLE
[OSPRH-10612] fix persistent field defaulting

### PR DESCRIPTION
**Pull request by vyzigold**

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by jlarriba** [comment]
To be able to cherry-pick this, https://github.com/openstack-k8s-operators/telemetry-operator/pull/468 needs to be cherry-picked before

**Comment by jlarriba** [comment]
It does not need to be cherry-picked, this is fixing an issue that never got into 18.0.0-proposed, so we are fine without cherry-pick

**Pull request merged**
